server:
  port: 8088
spring:
  datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      platform: h2
      username: sa
      password:
      driverClassName: org.h2.Driver
  h2:
    console:
      path: /console
      enabled: true